name: unsplash_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.1
  permission_asker: ^1.0.0+1
  photo_view: ^0.13.0
  date_format: ^2.0.6
  flutter_downloader: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true